"""blog Migration

Revision ID: eceded9f648c
Revises: fa1ace9556ae
Create Date: 2019-09-27 16:37:43.856113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eceded9f648c'
down_revision = 'fa1ace9556ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('writer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'writers', ['writer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'writer_id')
    # ### end Alembic commands ###
