"""column subscriber Migration

Revision ID: fe14f16c34dc
Revises: 8cc18f07fd91
Create Date: 2019-09-29 17:37:37.930799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe14f16c34dc'
down_revision = '8cc18f07fd91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_subscribers_name'), 'subscribers', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscribers_name'), table_name='subscribers')
    # ### end Alembic commands ###
